### ISSUE TITLE
Order of table of contents should same as markdown file.

### ISSUE THREAD

**Issue by wsdjeg** [lvht/tagbar-markdown#2]
hi @lvht , I think in the tagbar buffer, the order of items should same as it in markdown file.

**Comment by lvht** [comment]
yes, it is.

**Comment by wsdjeg** [comment]
But noe it has different order, you can have a try with 

https://github.com/SpaceVim/SpaceVim/blob/dev/README.md

**Comment by lvht** [comment]
the readme's phpcd link to https://github.com/rayburgemeestre/phpfolding.vim, not my phpcd.vim

**Comment by wsdjeg** [comment]
Readme need to update, but there is no phpcd in it.

**Comment by lvht** [comment]
i mean phpfold.vim

**Comment by wsdjeg** [comment]
Will update link, thanks.
