### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by GloverDonovan** [lvht/tagbar-markdown#6]
I would like to make modifications to the code, but it doesn't have a license.

https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

> Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

If you add a new license, you have to make sure that all contributors agree to it since they retain the copyright to their original code.

**Comment by lvht** [comment]
use the MIT

**Comment by GloverDonovan** [comment]
Thanks!
