### ISSUE TITLE
Can sorting be disabled?

### ISSUE THREAD

**Issue by naddeoa** [lvht/tagbar-markdown#9]
Is there any way of disabling the sorting in tagbar by default? It would be great to be able to get an overview in the order that it is defined in the file.

Thanks for the work.

**Comment by lvht** [comment]
It seems that the vim-tagbar do the sort. You can use <kbd>s</kbd> to switch the sort mode.

**Comment by naddeoa** [comment]
You're right. Looks like I can just add the following to my `ftplugin/markdown.vim` file

```vimscript
let g:tagbar_sort = 0
```
